name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  single_config:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build -V
    - name: Install
      run: cmake --install build --prefix=$HOME/mimicssl

  multi_config:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build --config $BUILD_TYPE
    - name: Test
      run: ctest --test-dir build -V -C $BUILD_TYPE
    - name: Install
      run: cmake --install build --config $BUILD_TYPE --prefix=$HOME/mimicssl
